---
name: frxz
version: 1
cron:
- description: cron test
  url: cron_off.php
  schedule: $26 day of month 00:00
  timezone: Beijing
- description: cron test
  url: cron_on.php
  schedule: $23 day of month 00:00
  timezone: Beijing